concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          ref: ${{ github.event.pull_request.head.repo.full_name == github.repository &&
            github.event.pull_request.head.ref || '' }}
      - uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: 20
      - run: corepack enable
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "GitHub Actions"
      - run: pnpm install --frozen-lockfile
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: pnpm verify
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: ignore
          name: Data from tests
          path: test-results/*/**
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: pnpm checkUnknownFiles
      - env:
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Push changed files
        run: pnpm dw-ci push-changed-files
      - if: github.ref == 'refs/heads/master'
        run: pnpm prepublishOnly
      - env:
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
        if: github.ref == 'refs/heads/master'
        run: pnpm prepublishOnly firefox
      - if: github.ref == 'refs/heads/master'
        run: zip -r ../chrome.zip .
        working-directory: dist/chrome
      - if: github.ref == 'refs/heads/master'
        run: zip -r ../firefox.zip .
        working-directory: dist/firefox
      - if: github.ref == 'refs/heads/master'
        run: git archive --output=dist/firefox-sources.zip HEAD
      - env:
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'
        name: Release
        run: pnpm semantic-release
name: build
on:
  pull_request: {}
  push:
    branches:
      - master
